version: 2
env:
  - CGO_ENABLED=1
  - GOPROXY=https://mirrors.aliyun.com/goproxy/,direct
builds:
  - id: linux-arm64
    main: ./
    binary: parca-agent
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -trimpath
      - -v
    ldflags:
      # https://goreleaser.com/customization/build/#reproducible-builds
      # {{.CommitDate}} is the date of the commit to make builds reproducible.
      - -X main.version={{.Version}} -X main.commit={{.FullCommit}} -X main.date={{.CommitDate}} -X main.goArch=arm64
      - -extldflags=-static
    tags:
      - osusergo
      - netgo
      - debugtracer
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- trimprefix .Version "v" }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    format: binary
    format_overrides:
      - goos: windows
        format: zip
    files:
      - 'LICENSE*'
      - 'README*'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Branch }}-{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: zmj64351508
    name: parca-agent
  prerelease: auto
  draft: false
  name_template: '{{ .Tag }}'