name: Android

on:
  push:
    tags:
      - v*-android

jobs:
  artifacts:
    name: Goreleaser release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    container:
      image: docker.io/goreleaser/goreleaser-cross:v1.22.4
      options: --privileged
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # https://github.com/actions/checkout/issues/766
      - name: Add repository directory to the git global config as a safe directory
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Run Goreleaser release
        run: goreleaser release --clean --verbose

      - name: Archive generated artifacts
        uses: actions/upload-artifact@v4
        with:
          name: parca-agent-dist-release
          if-no-files-found: error
          path: |
            dist/




 

